# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_checkout_addressing:
    path: /addressing
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            template: SyliusShopBundle:Checkout:addressing.html.twig
            form: sylius_checkout_addressing
            repository:
                method: find
                arguments: [expr:service('sylius.cart_provider').getCart()]
            state_machine:
                graph: sylius_order_checkout
                transition: address
            redirect: sylius_shop_checkout_shipping

sylius_shop_checkout_readdress:
    path: /readdress
    methods: [PUT]
    defaults:
        _controller: sylius.controller.order:applyStateMachineTransitionAction
        _sylius:
            flash: false
            state_machine:
                graph: sylius_order_checkout
                transition: readdress
            redirect: sylius_shop_checkout_addressing

sylius_shop_checkout_shipping:
    path: /shipping
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            template: SyliusShopBundle:Checkout:shipping.html.twig
            form:
                type: sylius_checkout_shipping
                options:
                    criteria: []
            repository:
                method: find
                arguments: [expr:service('sylius.cart_provider').getCart()]
            state_machine:
                graph: sylius_order_checkout
                transition: select_shipping
            redirect: sylius_shop_checkout_shipping
