sylius_admin_product_family:
    resource: |
        alias: sylius.product_family
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: update
        grid: sylius_admin_product_family
        permission: true
        vars:
          all:
              subheader: sylius.ui.manage_product_families
              templates:
                  form: "@SyliusAdmin/ProductFamily/_form.html.twig"
          index:
              icon: boxes
    type: sylius.resource
