# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: config.yml }

framework:
    router:
        strict_requirements: null

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver:
                    type: memcached
                    host: localhost
                    port: 11211

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
