# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_web:
    resource: "@SyliusWebBundle/Resources/config/routing/main.yml"

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /shop

sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin
