sylius_grid:
    grids:
        sylius_admin_product_family:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product_family.class%"
                    #repository:
                    #    method: createListQueryBuilder
                    #    arguments: ["%locale%"]
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: translation.name
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, translation.name]
            actions:
                main:
                    create:
                        type: create
                item:
                    add:
                        type: default
                        label: sylius.ui.create_product
                        icon: plus
                        options:
                            link:
                                route: sylius_admin_product_create_from_family
                                parameters:
                                    family: resource.code
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
