sylius_user_registration:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:createAction
        _sylius:
            form: sylius_user_registration
            event: register
            template: SyliusWebBundle:Frontend/User:register.html.twig
            redirect: sylius_homepage
            permission: false

sylius_user_request_password_reset:
    path: /resetting/request
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:requestPasswordResetAction
        _sylius:
            form: sylius_user_request_password_reset

sylius_user_password_reset:
    path: /resetting/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:resetPasswordAction

sylius_user_security_login:
    path: /login
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.security:loginAction
        _sylius:
            form: sylius_user_security_login
            template: SyliusWebBundle:Frontend/User:login.html.twig
            redirect: sylius_homepage

sylius_user_security_check:
    path: /login_check
    methods: [POST]
    defaults:
        _controller: sylius.controller.security:checkAction

sylius_user_security_logout:
    path: /logout
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.security:logoutAction
