# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski
#
sylius_backend_security_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security:loginAction
        template: 'SyliusWebBundle:Backend/Security:login.html.twig'

sylius_backend_security_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: sylius.controller.security:checkAction

sylius_backend_security_logout:
    path: /logout
    methods: [GET]
    defaults:
        _controller: sylius.controller.security:logoutAction
