sylius_user_request_password_reset:
    path: /request
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:requestPasswordResetAction
        _sylius:
            form: sylius_user_request_password_reset

sylius_user_password_reset:
    path: /{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:resetPasswordAction